### ISSUE TITLE
Geneate hash with indicating index

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/hashchain#5]
In the scenario that we want to get hash from a really large index, the current implementation would occupy to many memories which would cause the program crashing.

**Comment by jserv** [comment]
@afcidk, any idea about such improvements?

**Comment by afcidk** [comment]
I'm not sure why the current implementation would occupy too much memory since calculating the hashchain is divided into multiple basic parts (calculate the hash from one hash), which uses the same memory region and doesn't allocate more.

I would review the implementation first and find the reason why it occupies so much memory.

What I'm concerned about is that we cannot predict hash values, so the hashchain should be generated one-by-one, which may lead to poor response time if the index gets too big (though I still don't know what causes high memory usage)

I still don't come up with a better solution in generating hash with indicating index. The hash should only be calculated one-by-one. Otherwise the hashchain method should be regarded as dangerous if one can generate hash without the all previous information.

I think the improvements can be done much easier at application scale. Take the document attestation use case for example, maybe we can hide more information in the document (e.g. The current index), save the max index in the server to prevent infinite searching, etc.

**Comment by afcidk** [comment]
I've misunderstood the problem. I thought the problem lies in validating; however, it is creating the hash that occupies so much memory
